### PR TITLE
[diameter] add a few dictionaries

### PR DESCRIPTION
**Pull request by sebastiw**
Tiny PR to add dictionaries from 3GPP.

It took a couple of weeks but now most 3GPP interfaces are added along with IETF/ETSI/ITU-T definitions :partying_face: :champagne:

### CODE REVIEW

**Comment by alishir** [comment]
Hi @sebastiw,
Could you please guide me on how to use these directories in an Elixir project? Below is a snippet of my client configuration.

```Elixir
  defp init_diameter() do
    svc_opts = [
      {:"Origin-Host", "client.example.com"},
      {:"Origin-Realm", "example.com"},
      {:"Origin-State-Id", :diameter.origin_state_id()},
      {:"Vendor-Id", 0},
      {:"Product-Name", "Test diameter client"},
      {:"Auth-Application-Id", [4]},
      {:restrict_connections, false},
      {:strict_mbit, false},
      {:decode_format, :map},
      {:string_decode, false},
      {:application,
       [
         {:alias, :common},
         {:dictionary, @which_path?},
         {:module, Ocs.DiaCallback},
         {:call_mutates_state, false},
         {:answer_errors, :callback}
       ]}
    ]

    :ok = :diameter.start_service(@svc_name, svc_opts)

    transport_opts = [
      {:transport_module, :diameter_sctp},
      {:transport_config, [{:reuseaddr, true}, {:raddr, {127, 0, 0, 1}}, {:rport, 3868}]}
    ]

    {:ok, _} = :diameter.add_transport(@svc_name, {:connect, transport_opts})
  end
```

**Comment by sebastiw** [comment]
So when the dictionaries have been compiled (e.g. by `erlc dia_3gpp_ts_32299_GyRo.dia`, or by running `rebar3 compile` in this library) one should be able to add the dictionary name to the applications-field in the settings as `{:dictionary, :dia_3gpp_ts_32299_GyRo}`

I can take a better look later today

**Comment by alishir** [comment]
Thank you! I added otc to the dependencies. However, when I ran mix deps.get, I received the following messages:
```
Compile ASN1s: false
Compile DIA: false
```

**Comment by alishir** [comment]
Hi @sebastiw,
I discovered that the diameter-compiler plugin was commented out in the `rebar.conf` file. I added the latest version and submitted a pull request.

**Pull request merged**
